import * as THREE from 'three';
import {createGutterWater} from './gutter-water.js';
import {DRACOLoader} from './vendor/loaders/DRACOLoader.js';
import {RGBELoader} from './vendor/loaders/RGBELoader.js';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {createTown} from './npc-town.js';
import {buildFarSide,placeProps} from './town-blocks.js';
const $=id=>document.getElementById(id),canvas=$('world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#a8b7bc');scene.fog=new THREE.Fog('#a8b7bc',42,100);
const camera=new THREE.PerspectiveCamera(48,1,.1,160);const home=new THREE.Vector3(-21,1.4,24),target=new THREE.Vector3(-3,4.4,-3);camera.position.copy(home);camera.lookAt(target);
const direction=new THREE.Vector3();camera.getWorldDirection(direction);let yaw=Math.atan2(-direction.x,-direction.z),pitch=Math.asin(direction.y);const startYaw=yaw,startPitch=pitch;const strollPath=new THREE.CatmullRomCurve3([home,new THREE.Vector3(-14,1.4,16),new THREE.Vector3(-5.8,1.4,11),new THREE.Vector3(-4.7,1.48,7),new THREE.Vector3(-4.7,1.48,2.9)]);
const hemi=new THREE.HemisphereLight('#c5d7ef','#555b40',1.45);scene.add(hemi);
const sun=new THREE.DirectionalLight('#ffddb0',3.0);sun.position.set(-30,12,12);sun.target.position.set(-5,3,0);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-26,right:26,top:25,bottom:-20,near:1,far:85});sun.shadow.bias=-.00012;sun.shadow.normalBias=.035;
const porch=new THREE.PointLight('#ffc283',9,7,2);porch.position.set(-9,2.4,-3);scene.add(porch);
let town=null,rainAmount=0,rainTarget=0,stroll=false,strollT=0,last=0,moved=0,sound=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,loaded=false,drawCount=0;
$('motion').checked=reduced;const keys=new Set();let dragging=false,lx=0,ly=0;
function notice(t){$('notice').textContent=t;$('notice').classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>{$('notice').textContent='';$('notice').classList.remove('visible');},5000);}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);}addEventListener('resize',resize);resize();
const roadMaterials=[],roomMaterials=[];let gutterWater;
try{const hdr=await new RGBELoader().loadAsync('./assets/overcast.hdr');hdr.mapping=THREE.EquirectangularReflectionMapping;scene.environment=hdr;scene.environmentIntensity=.45;scene.background=hdr;scene.backgroundIntensity=.7;scene.backgroundBlurriness=.04;}catch(e){console.warn('Sky lighting unavailable',e);}
try{
 const draco=new DRACOLoader().setDecoderPath('./vendor/draco/');const assetLoader=new GLTFLoader().setDRACOLoader(draco);const assets=await Promise.all(['authored-street','street-setting'].map(name=>assetLoader.loadAsync('./assets/'+name+'/model.gltf')));const gltf={scene:new THREE.Group()};for(const asset of assets)gltf.scene.add(asset.scene);gltf.scene.updateMatrixWorld(true);try{buildFarSide(assets[1].scene,gltf.scene);}catch(e){console.warn('Far side unavailable',e);}const groups=new Map();
 gltf.scene.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];
 for(const m of mats){if(m.name==='WhiteDiffuse')m.color.set('#a1b196');if(m.name==='WhitePaint')m.color.set('#e2d8b8');if(m.name==='RoofTiles'||m.name==='Cape slate')m.color.set('#68736c');if(m.name==='Road')roadMaterials.push(m);if(m.name==='Warm room backing'||m.name==='Window linen')roomMaterials.push(m);if(m.name.startsWith('Distant pine')){m.alphaTest=.32;m.transparent=false;m.side=THREE.DoubleSide;m.depthWrite=true;}if(/leaf|leaves|grass|shrub|Fallen maple/i.test(m.name)){m.alphaTest=.45;m.transparent=false;m.side=THREE.DoubleSide;}if(m.name==='Glass'){m.color.set('#71827e');m.metalness=.25;m.roughness=.22;m.transparent=true;m.opacity=.6;m.depthWrite=false;}if(m.map)m.map.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());}
 // Authored architecture has baked contact shading; keep its indexed mesh and material groups.
 if(Array.isArray(o.material)){const mesh=new THREE.Mesh(o.geometry,o.material);mesh.applyMatrix4(o.matrixWorld);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);drawCount+=mats.length;return;}
 const key=o.material.uuid+'|'+Object.keys(o.geometry.attributes).sort().join(',');if(!groups.has(key))groups.set(key,{mat:o.material,items:[]});groups.get(key).items.push(o);
 });
 for(const {mat,items} of groups.values()){
  const byGeometry=new Map();for(const o of items){if(!byGeometry.has(o.geometry.uuid))byGeometry.set(o.geometry.uuid,[]);byGeometry.get(o.geometry.uuid).push(o);}
  const unique=[];
  for(const same of byGeometry.values()){
   if(same.length>3){const inst=new THREE.InstancedMesh(same[0].geometry,mat,same.length);same.forEach((o,i)=>inst.setMatrixAt(i,o.matrixWorld));inst.castShadow=!/grass/i.test(mat.name);inst.receiveShadow=true;scene.add(inst);drawCount++;}
   else for(const o of same){const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrixWorld);unique.push(g);}
  }
  if(unique.length){const geo=mergeGeometries(unique);if(!geo)throw new Error('Incompatible asset geometry');const mesh=mat.name==='Shallow gutter water'?(gutterWater=createGutterWater(geo,camera)):new THREE.Mesh(geo,mat);mesh.castShadow=!mat.name.startsWith('Distant pine');mesh.receiveShadow=true;scene.add(mesh);drawCount++;unique.forEach(g=>g.dispose());}
 }
 renderer.shadowMap.needsUpdate=true;loaded=true;$('loading').classList.add('done');
placeProps(new GLTFLoader(),scene).then(()=>{renderer.shadowMap.needsUpdate=true;}).catch(e=>console.warn('Street props unavailable',e));
 try{town=await createTown({scene,camera,loader:new GLTFLoader()});if(/[?&]qa\b/.test(location.search))window.__ld={town,camera,scene,setView(x,z,yw,pt){camera.position.set(x,1.4,z);yaw=yw;pitch=pt;}};}catch(e){console.warn('Residents unavailable',e);}
}catch(e){console.error(e);$('loading').innerHTML='<p>The authored scene could not load. Please reload to try again.</p>';}
const rainGeo=new THREE.BufferGeometry(),rainPos=new Float32Array(900*6);for(let i=0;i<900;i++){const x=Math.random()*45-25,y=Math.random()*17,z=Math.random()*30;rainPos.set([x,y,z,x-.045,y+.3,z],i*6);}rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const drops=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:'#c4d5db',transparent:true,opacity:0,depthWrite:false}));scene.add(drops);
function stop(){stroll=false;$('stroll').innerHTML='Take a stroll ↗';}
$('stroll').onclick=()=>{if(stroll)return stop();if(reduced)return notice('Reduce motion is on. You can still walk manually.');stroll=true;strollT=0;$('stroll').textContent='Pause stroll';};
$('home').onclick=()=>{stop();camera.position.copy(home);yaw=startYaw;pitch=startPitch;};
function weather(v){rainTarget=v;$('afternoon').setAttribute('aria-pressed',String(!v));$('rain').setAttribute('aria-pressed',String(!!v));$('mood').textContent=v?'Rain along the gutter.':'Late light on the porch.';}
$('afternoon').onclick=()=>weather(0);$('rain').onclick=()=>weather(1);
$('settings').onclick=()=>{const open=$('panel').hidden;$('panel').hidden=!open;$('settings').setAttribute('aria-expanded',String(open));};$('close-panel').onclick=()=>{$('panel').hidden=true;$('settings').setAttribute('aria-expanded','false');};$('stats-toggle').onchange=e=>$('stats').hidden=!e.target.checked;$('motion').onchange=e=>{reduced=e.target.checked;if(reduced)stop();};$('quality').onchange=()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,$('quality').value==='smooth'?1.5:1.25));resize();};
canvas.addEventListener('pointerdown',e=>{dragging=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-lx)*.003;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.003,-.65,.9);lx=e.clientX;ly=e.clientY;});
addEventListener('keydown',e=>{if(e.code==='KeyH'&&!e.target.matches('input,select'))document.body.classList.toggle('clean');if(e.target.matches('input,select,button'))return;if(/^(Key[WASD]|Arrow)/.test(e.code)&&!town?.busy){e.preventDefault();keys.add(e.code);stop();}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();dragging=false;});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);stop();};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);}
// Field recordings with crossfaded beds; sound begins only after an explicit click.
let ac,master,bird,rain,buffers={},nextBird=0,nextRain=0,stepDistance=0;
function bed(name,out,time){const src=ac.createBufferSource(),gain=ac.createGain(),buf=buffers[name],fade=3;src.buffer=buf;src.connect(gain).connect(out);gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(1,time+fade);gain.gain.setValueAtTime(1,time+buf.duration-fade);gain.gain.linearRampToValueAtTime(0,time+buf.duration);src.start(time);src.onended=()=>{src.disconnect();gain.disconnect();};return time+buf.duration-fade;}
$('sound').onclick=async()=>{if(!ac){$('sound').disabled=true;$('sound').textContent='Loading sound…';ac=new AudioContext();master=ac.createGain();master.gain.value=.55;master.connect(ac.destination);bird=ac.createGain();rain=ac.createGain();const birdPosition=ac.createPanner();birdPosition.panningModel='HRTF';birdPosition.refDistance=10;birdPosition.rolloffFactor=.5;birdPosition.positionX.value=5;birdPosition.positionY.value=3;birdPosition.positionZ.value=3;bird.connect(birdPosition).connect(master);rain.connect(master);try{await Promise.all(['birds','rain','stone01','leaves01'].map(async n=>{const r=await fetch('./assets/audio/'+n+'.ogg');if(!r.ok)throw Error('Audio');buffers[n]=await ac.decodeAudioData(await r.arrayBuffer());let peak=0;for(let c=0;c<buffers[n].numberOfChannels;c++)for(const v of buffers[n].getChannelData(c))peak=Math.max(peak,Math.abs(v));const gain=Math.min(20,.65/Math.max(peak,.001));for(let c=0;c<buffers[n].numberOfChannels;c++){const a=buffers[n].getChannelData(c);for(let i=0;i<a.length;i++)a[i]*=gain;}}));nextBird=nextRain=ac.currentTime;$('sound').disabled=false;}catch(e){notice('Sound could not load. Please reload and retry.');await ac.close();ac=null;$('sound').disabled=false;$('sound').textContent='Sound off';return;}}sound=!sound;if(sound)await ac.resume();else await ac.suspend();$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));};
function audio(dt,dist){if(!sound||!buffers.rain||ac.state!=='running')return;const t=ac.currentTime;for(const [k,v] of Object.entries({positionX:camera.position.x,positionY:camera.position.y,positionZ:camera.position.z,forwardX:-Math.sin(yaw)*Math.cos(pitch),forwardY:Math.sin(pitch),forwardZ:-Math.cos(yaw)*Math.cos(pitch),upX:0,upY:1,upZ:0}))ac.listener[k].setTargetAtTime(v,t,.05);if(nextBird<t+.2)nextBird=bed('birds',bird,Math.max(t,nextBird));if(nextRain<t+.2)nextRain=bed('rain',rain,Math.max(t,nextRain));bird.gain.setTargetAtTime(.5*(1-rainAmount),t,.4);rain.gain.setTargetAtTime(.6*rainAmount,t,.4);if(dist>.3)return;stepDistance+=dist;if(stepDistance>.7){stepDistance=0;const src=ac.createBufferSource(),gain=ac.createGain();src.buffer=buffers[((camera.position.z<7.38&&Math.abs(camera.position.x+4.7)>1.25)||camera.position.z>20)?'leaves01':'stone01'];gain.gain.value=.25;src.connect(gain).connect(master);src.start();src.onended=()=>{src.disconnect();gain.disconnect();};}}
document.addEventListener('visibilitychange',()=>{keys.clear();if(ac){if(document.hidden)ac.suspend();else if(sound)ac.resume();}last=0;});
function tick(now){requestAnimationFrame(tick);if(document.hidden)return;const fps=$('quality').value==='smooth'?60:30;if(now-last<1000/fps-1)return;const dt=Math.min((now-last)/1000,.05)||.033;last=now;if(!loaded)return;const before=camera.position.clone();
 if(stroll){strollT=Math.min(1,strollT+dt/34);camera.position.copy(strollPath.getPointAt(strollT));if(!dragging){camera.lookAt(-5,THREE.MathUtils.lerp(4.4,2.4,strollT),-3);camera.getWorldDirection(direction);yaw=Math.atan2(-direction.x,-direction.z);pitch=Math.asin(direction.y);}if(strollT>=1)stop();}
 if(town?.busy){keys.clear();}
 let f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),side=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));const len=Math.hypot(f,side)||1;f/=len;side/=len;camera.position.x=THREE.MathUtils.clamp(camera.position.x+(-Math.sin(yaw)*f+Math.cos(yaw)*side)*dt*1.7,-27,24);camera.position.z=THREE.MathUtils.clamp(camera.position.z+(-Math.cos(yaw)*f-Math.sin(yaw)*side)*dt*1.7,1.8,26);if(camera.position.z<4&&before.z<4)for(const fence of [-17.3,8.3])if((before.x-fence)*(camera.position.x-fence)<0)camera.position.x=before.x;const z=camera.position.z;const ground=(z>7.38&&z<9.03)||(z>18.44&&z<19.88)?.12:(Math.abs(camera.position.x+4.7)<1.2&&z<7.36?.08:0);if(town)town.collide(camera.position);camera.position.y=THREE.MathUtils.damp(camera.position.y,1.4+ground,12,dt);camera.rotation.set(pitch,yaw,0,'YXZ');
 rainAmount=THREE.MathUtils.damp(rainAmount,rainTarget,1.5,dt);sun.intensity=THREE.MathUtils.lerp(3,.35,rainAmount);hemi.intensity=THREE.MathUtils.lerp(1.45,.85,rainAmount);renderer.toneMappingExposure=THREE.MathUtils.lerp(1.1,.8,rainAmount);drops.material.opacity=rainAmount*.28;for(const m of roomMaterials)m.emissiveIntensity=THREE.MathUtils.lerp(.14,.55,rainAmount);for(const m of roadMaterials)m.roughness=THREE.MathUtils.lerp(.82,.28,rainAmount);if(!reduced&&rainAmount>.01){for(let i=0;i<900;i++){rainPos[i*6+1]-=dt*9;rainPos[i*6+4]-=dt*9;if(rainPos[i*6+1]<0){rainPos[i*6+1]=17;rainPos[i*6+4]=17.3;}}rainGeo.attributes.position.needsUpdate=true;}audio(dt,camera.position.distanceTo(before));gutterWater?.userData.update(now/1000,rainAmount,$('quality').value==='smooth',reduced);town?.update(dt,{rain:rainAmount,reduced});renderer.render(scene,camera);if(!$('stats').hidden)$('stats').textContent=`${renderer.info.render.calls} draws · ${(renderer.info.render.triangles/1000).toFixed(0)}k triangles · ${fps} fps cap`;
}requestAnimationFrame(tick);
