import * as THREE from 'three';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {DRACOLoader} from './vendor/loaders/DRACOLoader.js';
import {RGBELoader} from './vendor/loaders/RGBELoader.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {buildDrainWorld} from './drain-world.js';
import {createDrainWater} from './drain-water.js';
import {createDrainFinish} from './drain-finish.js';
import {newEncounter,stepEncounter,interact,boatPosition,boatPose,boatHeading,constrainPosition,followBoatPosition,beginLooking,cinematic} from './drain-state.js';
import {createPresence} from './drain-presence.js';
const $=id=>document.getElementById(id),canvas=$('world'),keys=new Set();let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch(e){$('loading').innerHTML='<p>WebGL is unavailable. <a href="georgie-film.html">Watch the cinematic study instead</a>.</p>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.shadowMap.autoUpdate=false;renderer.info.autoReset=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#899b9d');scene.fog=new THREE.FogExp2('#788888',.021);
let finish;
const camera=new THREE.PerspectiveCamera(57,1,.025,110),home=new THREE.Vector3(-4.75,1.03,1.45);let yaw=-.52,pitch=-.52,crouched=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,loaded=false,last=0,elapsed=0,state=newEncounter(),following=false,dragging=false,lx=0,ly=0;camera.position.copy(home);$('motion').checked=reduced;
scene.add(new THREE.HemisphereLight('#c2d1dc','#293328',.75));const sun=new THREE.DirectionalLight('#cbd8db',.7);sun.position.set(-9,13,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:20,bottom:-15,near:1,far:60});sun.shadow.normalBias=.014;sun.shadow.bias=-.0001;scene.add(sun);
const porch=new THREE.PointLight('#ffc788',0,10,2);porch.position.set(-9,2.5,-12);scene.add(porch);
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);if(finish){const size=renderer.getDrawingBufferSize(new THREE.Vector2());finish.resize(size.x,size.y);}}addEventListener('resize',resize);finish=createDrainFinish(renderer,camera);resize();
function notice(s){$('notice').textContent=s;$('notice').classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').classList.remove('visible'),4500);}
const manager=new THREE.LoadingManager(),tl=new THREE.TextureLoader(manager),maps={};const specs={paper:'drain/Paper001_1K-JPG_Color.jpg',paperNormal:'drain/Paper001_1K-JPG_NormalGL.jpg',paperRough:'drain/Paper001_1K-JPG_Roughness.jpg',asphalt:'aerial_asphalt_01_Diffuse.jpg',asphaltNormal:'aerial_asphalt_01_nor_gl.jpg',stone:'drain/concrete-color.jpg',stoneNormal:'drain/concrete-normal.jpg',stoneRough:'drain/concrete-rough.jpg',pavement:'concrete_pavement_diff.jpg',pavementNormal:'concrete_pavement_nor_gl.jpg',ground:'forrest_ground_01_Diffuse.jpg',groundNormal:'forrest_ground_01_nor_gl.jpg',brick:'red_brick_diff.jpg',brickNormal:'red_brick_nor_gl.jpg',bark:'bark_brown_02_Diffuse.jpg',barkNormal:'bark_brown_02_nor_gl.jpg',leaf:'leaves/LeafSet027_1K-JPG_Color.jpg',leafAlpha:'leaves/LeafSet027_1K-JPG_Opacity.jpg',leafNormal:'leaves/LeafSet027_1K-JPG_NormalGL.jpg'};
let world,water,presence,lookStart=null;
try{
 await Promise.all(Object.entries(specs).map(async([key,path])=>{const m=await tl.loadAsync('assets/'+path);if(!/Normal|Alpha|Rough/.test(key))m.colorSpace=THREE.SRGBColorSpace;m.wrapS=m.wrapT=THREE.RepeatWrapping;m.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());m.userData.path='assets/'+path;maps[key]=m;}));
 world=buildDrainWorld(maps);scene.add(world.root);
 // Merge leaf geometry after world transforms, retaining photographed UV variants.
 world.root.updateMatrixWorld(true);for(const group of [world.leafGroup,world.canopy]){const parts=group.children.map(o=>o.geometry.clone().applyMatrix4(o.matrixWorld));const mesh=new THREE.Mesh(mergeGeometries(parts),group.children[0].material);mesh.receiveShadow=true;mesh.castShadow=group===world.canopy;scene.add(mesh);group.visible=false;parts.forEach(g=>g.dispose());}
 water=createDrainWater(camera);scene.add(water);
 presence=await createPresence(tl);scene.add(presence.mesh);
 loaded=true;$('loading').classList.add('done');$('loading').setAttribute('aria-hidden','true');$('action').disabled=false;renderer.shadowMap.needsUpdate=true;
}catch(e){console.error(e);$('loading').innerHTML='<p>The 3D scene could not load. <a href="georgie.html">Reload</a> or <a href="georgie-film.html">watch the film study</a>.</p>';}
// Background streams after the playable foreground. Only authored architecture, planting and distant context are retained.
(async()=>{try{const hdr=await new RGBELoader().loadAsync('assets/overcast.hdr');hdr.mapping=THREE.EquirectangularReflectionMapping;scene.environment=hdr;scene.environmentIntensity=.75;scene.background=hdr;scene.backgroundIntensity=.55;scene.backgroundBlurriness=.07;const loader=new GLTFLoader().setDRACOLoader(new DRACOLoader().setDecoderPath('vendor/draco/'));const assets=await Promise.all(['authored-street','street-setting'].map(n=>loader.loadAsync('assets/'+n+'/model.gltf')));const groups=new Map(),shift=new THREE.Matrix4().makeTranslation(0,.18,-9.2);
 for(let a=0;a<assets.length;a++){assets[a].scene.updateMatrixWorld(true);assets[a].scene.traverse(o=>{if(!o.isMesh)return;const n=[o.name,o.parent?.name,o.parent?.parent?.name].join(' ');if(a===0&&!/Authored|chair|planter|shrub|fern/i.test(n))return;if(a===1&&/Opposite|curb|driveway|ground|yard|Living.lawn.surface/i.test(n))return;
 const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials){if(m.name==='WhiteDiffuse')m.color.set('#89998b');if(m.name==='WhitePaint')m.color.set('#d4ccb4');if(/RoofTiles|Cape slate/.test(m.name))m.color.set('#56615f');if(/leaf|leaves|shrub|pine/i.test(m.name)){m.alphaTest=.4;m.transparent=false;m.side=THREE.DoubleSide;}if(/Warm room|Window linen/.test(m.name))m.emissiveIntensity=0;}
 const g=o.geometry.clone();g.applyMatrix4(o.matrixWorld);g.applyMatrix4(shift);if(Array.isArray(o.material)){const mesh=new THREE.Mesh(g,o.material);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);}else{const k=o.material.uuid+'|'+Object.keys(g.attributes).join(',');if(!groups.has(k))groups.set(k,{mat:o.material,gs:[]});groups.get(k).gs.push(g.index?g.toNonIndexed():g);}
 });}
 for(const {mat,gs} of groups.values()){const geo=mergeGeometries(gs);if(geo){const mesh=new THREE.Mesh(geo,mat);mesh.castShadow=!/pine/i.test(mat.name);mesh.receiveShadow=true;mesh.userData.skipDrainReflection=/grass|pine|leaf|leaves|shrub|fern/i.test(mat.name);scene.add(mesh);}gs.forEach(g=>g.dispose());}renderer.shadowMap.needsUpdate=true;
 }catch(e){console.warn(e);notice('Street backdrop could not load; the drain scene is still playable.');}})();
// Rain and localized impact rings; no full fluid solver.
const rainCount=750,rp=new Float32Array(rainCount*6);for(let i=0;i<rainCount;i++){const x=Math.random()*40-20,y=Math.random()*10,z=Math.random()*18-5;rp.set([x,y,z,x-.015,y+.13,z],i*6);}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.BufferAttribute(rp,3));const rain=new THREE.LineSegments(rg,new THREE.LineBasicMaterial({color:'#c4d1d2',transparent:true,opacity:.22,depthWrite:false}));scene.add(rain);
const splashMaterial=new THREE.MeshBasicMaterial({color:'#b2c1ba',transparent:true,opacity:.11,depthWrite:false,side:THREE.DoubleSide}),splash=new THREE.InstancedMesh(new THREE.RingGeometry(.8,1,16),splashMaterial,60),dummy=new THREE.Object3D();scene.add(splash);const splashes=Array.from({length:60},()=>({x:Math.random()*20-10,z:.1+Math.random()*4,phase:Math.random()}));
function reset(){following=false;state=newEncounter();camera.position.copy(home);yaw=-.52;pitch=-.52;crouched=false;$('crouch').textContent='Crouch · C';$('crouch').setAttribute('aria-pressed','false');$('black').style.opacity=0;$('black').style.pointerEvents='none';$('black').setAttribute('aria-hidden','true');$('aftermath').hidden=true;keys.clear();if(presence)presence.mesh.visible=false;lookStart=null;document.body.classList.remove('cinematic');camera.fov=57;camera.updateProjectionMatrix();canvas.focus();}
function action(){
 if(!loaded||cinematic(state))return;
 const b=world.boat.position,nearBoat=Math.hypot(camera.position.x-b.x,camera.position.z-b.z)<2.4,nearDrain=Math.hypot(camera.position.x,camera.position.z)<1.65;
 if(state.phase==='floating'||(state.phase==='waiting'&&(!nearDrain||following))){following=!following;if(following){crouched=false;updateCrouch();}canvas.focus();return;}
 interact(state,nearBoat,nearDrain);
 if(state.phase==='ready'&&!nearBoat)notice('Move closer to the paper boat.');
 canvas.focus();
}
function updateCrouch(){$('crouch').textContent=crouched?'Stand · C':'Crouch · C';$('crouch').setAttribute('aria-pressed',String(crouched));}
$('black').onclick=()=>{if(state.phase==='after')reset();};$('action').onclick=action;$('reset').onclick=reset;$('again').onclick=reset;$('crouch').onclick=()=>{if(cinematic(state))return;following=false;crouched=!crouched;updateCrouch();canvas.focus();};$('motion').onchange=e=>reduced=e.target.checked;$('quality').onchange=()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,$('quality').value==='smooth'?1.5:1.25));resize();};$('settings').onclick=()=>{$('panel').hidden=!$('panel').hidden;$('settings').setAttribute('aria-expanded',String(!$('panel').hidden));};$('close-panel').onclick=()=>{$('panel').hidden=true;$('settings').setAttribute('aria-expanded','false');};$('stats-toggle').onchange=e=>$('stats').hidden=!e.target.checked;
canvas.addEventListener('pointerdown',e=>{if(cinematic(state))return;following=false;dragging=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-lx)*.003;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.003,-1.35,.8);lx=e.clientX;ly=e.clientY;});
addEventListener('keydown',e=>{if(e.code==='Escape'){reset();return;}if(cinematic(state))return;if(e.target.matches('input,select,textarea,[contenteditable=true]'))return;if(e.code==='KeyE'&&!e.repeat)action();if(e.code==='KeyC'&&!e.repeat){following=false;crouched=!crouched;updateCrouch();}if(e.code==='KeyH')document.body.classList.toggle('clean');if(/^(Key[WASD]|Arrow)/.test(e.code)){e.preventDefault();following=false;if(!e.repeat){const f=Number(/KeyW|ArrowUp/.test(e.code))-Number(/KeyS|ArrowDown/.test(e.code)),side=Number(/KeyD|ArrowRight/.test(e.code))-Number(/KeyA|ArrowLeft/.test(e.code));if(state.phase!=='ending'){const step=crouched?.022:.045,pos=constrainPosition(camera.position.x+(-Math.sin(yaw)*f+Math.cos(yaw)*side)*step,camera.position.z+(-Math.cos(yaw)*f-Math.sin(yaw)*side)*step);camera.position.x=pos.x;camera.position.z=pos.z;}}keys.add(e.code);}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();dragging=false;});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{if(cinematic(state))return;following=false;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);}
let ac,master,ambient,drain,filter,recording,stepBuffer,sound=false,nextBed=0,stepDist=0,lastDrip=-1;
function scheduleBed(time){const src=ac.createBufferSource(),g=ac.createGain();src.buffer=recording;src.connect(g);g.connect(ambient);g.connect(filter);g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(1,time+3);g.gain.setValueAtTime(1,time+recording.duration-3);g.gain.linearRampToValueAtTime(0,time+recording.duration);src.start(time);src.onended=()=>{src.disconnect();g.disconnect();};return time+recording.duration-3;}
$('sound').onclick=async()=>{const btn=$('sound');btn.disabled=true;try{if(!ac){ac=new AudioContext();master=ac.createGain();master.gain.value=.6;master.connect(ac.destination);ambient=ac.createGain();ambient.gain.value=.55;ambient.connect(master);filter=ac.createBiquadFilter();filter.type='lowpass';filter.frequency.value=850;drain=ac.createPanner();drain.panningModel='HRTF';drain.refDistance=.7;drain.rolloffFactor=1;drain.positionX.value=0;drain.positionY.value=.1;drain.positionZ.value=-.2;filter.connect(drain).connect(master);const load=async path=>{const r=await fetch(path);if(!r.ok)throw Error('audio');const b=await ac.decodeAudioData(await r.arrayBuffer());let peak=0;for(let i=0;i<b.numberOfChannels;i++)for(const v of b.getChannelData(i))peak=Math.max(peak,Math.abs(v));const g=Math.min(20,.65/Math.max(peak,.001));for(let i=0;i<b.numberOfChannels;i++){const a=b.getChannelData(i);for(let j=0;j<a.length;j++)a[j]*=g;}return b;};[recording,stepBuffer]=await Promise.all([load('assets/audio/rain.ogg'),load('assets/audio/stone01.ogg')]);nextBed=ac.currentTime;}sound=!sound;if(sound)await ac.resume();else await ac.suspend();btn.textContent=sound?'Sound on':'Sound off';btn.setAttribute('aria-pressed',String(sound));}catch(e){if(ac)await ac.close();ac=null;sound=false;btn.textContent='Retry sound';notice('Audio did not load. You can keep exploring and retry.');}finally{btn.disabled=false;}};
function audio(dist){if(!ac||!sound||ac.state!=='running'||!recording)return;const t=ac.currentTime;if(nextBed<t+.2)nextBed=scheduleBed(Math.max(t,nextBed));for(const[k,v]of Object.entries({positionX:camera.position.x,positionY:camera.position.y,positionZ:camera.position.z,forwardX:-Math.sin(yaw)*Math.cos(pitch),forwardY:Math.sin(pitch),forwardZ:-Math.cos(yaw)*Math.cos(pitch),upX:0,upY:1,upZ:0}))ac.listener[k]?.setTargetAtTime(v,t,.05);if(state.phase==='after'){master.gain.cancelScheduledValues(t);master.gain.setValueAtTime(0,t);}else master.gain.setTargetAtTime(.6,t,.12);ambient.gain.setTargetAtTime(cinematic(state)?.08:.55,t,.8);filter.frequency.setTargetAtTime(cinematic(state)?360:850,t,.6);const drip=Math.floor(state.beatTime/1.27);if(state.phase==='looking'&&state.beatTime>2.2&&drip!==lastDrip){lastDrip=drip;const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(920,t);o.frequency.exponentialRampToValueAtTime(380,t+.12);g.gain.setValueAtTime(.025,t);g.gain.exponentialRampToValueAtTime(.0001,t+.22);o.connect(g).connect(drain);o.start(t);o.stop(t+.23);o.onended=()=>{o.disconnect();g.disconnect();};}stepDist+=dist;if(stepDist>.65){stepDist=0;const s=ac.createBufferSource(),g=ac.createGain();s.buffer=stepBuffer;g.gain.value=crouched?.07:.14;s.connect(g).connect(master);s.start();s.onended=()=>{s.disconnect();g.disconnect();};}}
document.addEventListener('visibilitychange',()=>{keys.clear();last=0;if(ac){if(document.hidden)ac.suspend();else if(sound)ac.resume();}});
let previousPhase='',meterStart=0,meterFrames=0,measuredFps=0;
function tick(now){requestAnimationFrame(tick);if(document.hidden)return;const fps=$('quality').value==='smooth'?60:30;if(now-last<1000/fps-1)return;const dt=Math.min((now-last)/1000,.06)||.033;last=now;if(!loaded)return;elapsed+=dt;if(!meterStart)meterStart=now;meterFrames++;if(now-meterStart>=1000){measuredFps=Math.round(meterFrames*1000/(now-meterStart));meterFrames=0;meterStart=now;}
 const before=camera.position.clone();
 if(following&&(state.phase==='floating'||state.phase==='waiting')){
  const boat=boatPosition(state.boatTime),pos=followBoatPosition(camera.position,boat,dt);camera.position.x=pos.x;camera.position.z=pos.z;
  const dx=boat.x-camera.position.x,dz=boat.z-camera.position.z,targetYaw=Math.atan2(-dx,-dz),delta=Math.atan2(Math.sin(targetYaw-yaw),Math.cos(targetYaw-yaw));yaw+=delta*(1-Math.exp(-dt*4));pitch=THREE.MathUtils.damp(pitch,Math.atan2(.10-camera.position.y,Math.hypot(dx,dz)),4,dt);
  if(state.phase==='waiting'&&pos.arrived){following=false;beginLooking(state);}
 }
 if(!following&&!cinematic(state)){let f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),s=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));const len=Math.hypot(f,s)||1,speed=crouched?.7:1.65;const pos=constrainPosition(camera.position.x+(-Math.sin(yaw)*f+Math.cos(yaw)*s)*dt*speed/len,camera.position.z+(-Math.cos(yaw)*f-Math.sin(yaw)*s)*dt*speed/len);camera.position.x=pos.x;camera.position.z=pos.z;}if(!cinematic(state))camera.position.y=THREE.MathUtils.damp(camera.position.y,crouched?.29:1.03,9,dt);
 const near=Math.hypot(camera.position.x,camera.position.z)<1.65;stepEncounter(state,dt,near,crouched);const bp=boatPose(state.boatTime);
 if(cinematic(state)){
  if(!lookStart){lookStart={position:camera.position.clone(),yaw,pitch};keys.clear();dragging=false;document.body.classList.add('cinematic');$('panel').hidden=true;}
  const t=state.phase==='looking'?Math.min(1,state.beatTime/2.2):1,e=t*t*t*(t*(t*6-15)+10);
  camera.position.lerpVectors(lookStart.position,new THREE.Vector3(.08,.22,.34),e);
  const targetYaw=0,targetPitch=Math.atan2(.09-.22,.34+.28);yaw=lookStart.yaw+Math.atan2(Math.sin(targetYaw-lookStart.yaw),Math.cos(targetYaw-lookStart.yaw))*e;pitch=THREE.MathUtils.lerp(lookStart.pitch,targetPitch,e);camera.fov=57-6*e;camera.updateProjectionMatrix();
 }
 camera.rotation.set(pitch,yaw,0,'YXZ');
 world.boat.position.set(bp.x,bp.y+(reduced||bp.drop?0:Math.sin(elapsed*2.6)*.0015),bp.z);world.boat.rotation.set(0,boatHeading(state.boatTime),bp.tip);world.boat.visible=bp.visible;presence.update(state,elapsed,reduced,camera);
 $('black').style.opacity=state.phase==='after'?1:0;$('black').style.pointerEvents=state.phase==='after'?'auto':'none';$('black').setAttribute('aria-hidden',String(state.phase!=='after'));
 if(state.phase!==previousPhase){$('objective').textContent={ready:'Release the boat into the gutter.',floating:'Follow the paper boat.',waiting:'The boat disappeared. Look inside.',looking:'',revealed:'',ending:'',after:''}[state.phase];previousPhase=state.phase;}
 const nearBoat=Math.hypot(camera.position.x-bp.x,camera.position.z-bp.z)<2.4;const label=state.phase==='ready'?(nearBoat?'Release boat · E':'Approach the boat'):state.phase==='floating'?(following?'Stop following · E':'Follow the boat · E'):state.phase==='waiting'?(following?'Stop following · E':near?'Look inside · E':'Walk to drain · E'):'Encounter in progress';$('action').textContent=label;$('action').disabled=state.phase==='ready'?!nearBoat:cinematic(state);

 if(state.phase==='after'){audio(0);return;}
 if(!reduced){for(let i=0;i<rainCount;i++){rp[i*6+1]-=dt*7;rp[i*6+4]-=dt*7;if(rp[i*6+1]<0){rp[i*6+1]=10;rp[i*6+4]=10.13;}}rg.attributes.position.needsUpdate=true;for(let i=0;i<splashes.length;i++){const s=splashes[i],a=(elapsed*.9+s.phase)%1,r=.015+a*.095;dummy.position.set(s.x,.028,s.z);dummy.rotation.set(-Math.PI/2,0,0);dummy.scale.setScalar(r*(1-a*.3));dummy.updateMatrix();splash.setMatrixAt(i,dummy.matrix);}splash.instanceMatrix.needsUpdate=true;}rain.visible=splash.visible=!reduced;water.userData.update(elapsed,$('quality').value==='smooth',reduced);water.userData.setBoat(bp.x,bp.z,boatHeading(state.boatTime),state.phase==='floating'&&bp.drop===0?1:0,bp.visible&&bp.drop===0);audio(Math.hypot(camera.position.x-before.x,camera.position.z-before.z));renderer.info.reset();finish.render(scene,elapsed,reduced);if(!$('stats').hidden)$('stats').textContent=`${renderer.info.render.calls} draws · ${(renderer.info.render.triangles/1000).toFixed(0)}k triangles · ${measuredFps} fps · cap ${fps}`;
}requestAnimationFrame(tick);
